/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MyCommitteeRouteImport } from './routes/my-committee'
import { Route as MyCirclesRouteImport } from './routes/my-circles'
import { Route as MediaHubRouteImport } from './routes/media-hub'
import { Route as ManhajRouteImport } from './routes/manhaj'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DutiesRouteImport } from './routes/duties'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as AlaBaseeraRouteImport } from './routes/ala-baseera'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworkIndexRouteImport } from './routes/network.index'
import { Route as StudentTokenRouteImport } from './routes/student.$token'
import { Route as NetworkUnitIdRouteImport } from './routes/network.$unitId'
import { Route as MosqueMosqueIdRouteImport } from './routes/mosque.$mosqueId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCommitteeRoute = MyCommitteeRouteImport.update({
  id: '/my-committee',
  path: '/my-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCirclesRoute = MyCirclesRouteImport.update({
  id: '/my-circles',
  path: '/my-circles',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaHubRoute = MediaHubRouteImport.update({
  id: '/media-hub',
  path: '/media-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ManhajRoute = ManhajRouteImport.update({
  id: '/manhaj',
  path: '/manhaj',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DutiesRoute = DutiesRouteImport.update({
  id: '/duties',
  path: '/duties',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const AlaBaseeraRoute = AlaBaseeraRouteImport.update({
  id: '/ala-baseera',
  path: '/ala-baseera',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkIndexRoute = NetworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NetworkRoute,
} as any)
const StudentTokenRoute = StudentTokenRouteImport.update({
  id: '/student/$token',
  path: '/student/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkUnitIdRoute = NetworkUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => NetworkRoute,
} as any)
const MosqueMosqueIdRoute = MosqueMosqueIdRouteImport.update({
  id: '/mosque/$mosqueId',
  path: '/mosque/$mosqueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ala-baseera': typeof AlaBaseeraRoute
  '/competition': typeof CompetitionRoute
  '/design-system': typeof DesignSystemRoute
  '/duties': typeof DutiesRoute
  '/finance': typeof FinanceRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/manhaj': typeof ManhajRoute
  '/media-hub': typeof MediaHubRoute
  '/my-circles': typeof MyCirclesRoute
  '/my-committee': typeof MyCommitteeRoute
  '/network': typeof NetworkRouteWithChildren
  '/no-access': typeof NoAccessRoute
  '/register': typeof RegisterRoute
  '/mosque/$mosqueId': typeof MosqueMosqueIdRoute
  '/network/$unitId': typeof NetworkUnitIdRoute
  '/student/$token': typeof StudentTokenRoute
  '/network/': typeof NetworkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ala-baseera': typeof AlaBaseeraRoute
  '/competition': typeof CompetitionRoute
  '/design-system': typeof DesignSystemRoute
  '/duties': typeof DutiesRoute
  '/finance': typeof FinanceRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/manhaj': typeof ManhajRoute
  '/media-hub': typeof MediaHubRoute
  '/my-circles': typeof MyCirclesRoute
  '/my-committee': typeof MyCommitteeRoute
  '/no-access': typeof NoAccessRoute
  '/register': typeof RegisterRoute
  '/mosque/$mosqueId': typeof MosqueMosqueIdRoute
  '/network/$unitId': typeof NetworkUnitIdRoute
  '/student/$token': typeof StudentTokenRoute
  '/network': typeof NetworkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ala-baseera': typeof AlaBaseeraRoute
  '/competition': typeof CompetitionRoute
  '/design-system': typeof DesignSystemRoute
  '/duties': typeof DutiesRoute
  '/finance': typeof FinanceRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/manhaj': typeof ManhajRoute
  '/media-hub': typeof MediaHubRoute
  '/my-circles': typeof MyCirclesRoute
  '/my-committee': typeof MyCommitteeRoute
  '/network': typeof NetworkRouteWithChildren
  '/no-access': typeof NoAccessRoute
  '/register': typeof RegisterRoute
  '/mosque/$mosqueId': typeof MosqueMosqueIdRoute
  '/network/$unitId': typeof NetworkUnitIdRoute
  '/student/$token': typeof StudentTokenRoute
  '/network/': typeof NetworkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ala-baseera'
    | '/competition'
    | '/design-system'
    | '/duties'
    | '/finance'
    | '/library'
    | '/login'
    | '/manhaj'
    | '/media-hub'
    | '/my-circles'
    | '/my-committee'
    | '/network'
    | '/no-access'
    | '/register'
    | '/mosque/$mosqueId'
    | '/network/$unitId'
    | '/student/$token'
    | '/network/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ala-baseera'
    | '/competition'
    | '/design-system'
    | '/duties'
    | '/finance'
    | '/library'
    | '/login'
    | '/manhaj'
    | '/media-hub'
    | '/my-circles'
    | '/my-committee'
    | '/no-access'
    | '/register'
    | '/mosque/$mosqueId'
    | '/network/$unitId'
    | '/student/$token'
    | '/network'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ala-baseera'
    | '/competition'
    | '/design-system'
    | '/duties'
    | '/finance'
    | '/library'
    | '/login'
    | '/manhaj'
    | '/media-hub'
    | '/my-circles'
    | '/my-committee'
    | '/network'
    | '/no-access'
    | '/register'
    | '/mosque/$mosqueId'
    | '/network/$unitId'
    | '/student/$token'
    | '/network/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlaBaseeraRoute: typeof AlaBaseeraRoute
  CompetitionRoute: typeof CompetitionRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DutiesRoute: typeof DutiesRoute
  FinanceRoute: typeof FinanceRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ManhajRoute: typeof ManhajRoute
  MediaHubRoute: typeof MediaHubRoute
  MyCirclesRoute: typeof MyCirclesRoute
  MyCommitteeRoute: typeof MyCommitteeRoute
  NetworkRoute: typeof NetworkRouteWithChildren
  NoAccessRoute: typeof NoAccessRoute
  RegisterRoute: typeof RegisterRoute
  MosqueMosqueIdRoute: typeof MosqueMosqueIdRoute
  StudentTokenRoute: typeof StudentTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-committee': {
      id: '/my-committee'
      path: '/my-committee'
      fullPath: '/my-committee'
      preLoaderRoute: typeof MyCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-circles': {
      id: '/my-circles'
      path: '/my-circles'
      fullPath: '/my-circles'
      preLoaderRoute: typeof MyCirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-hub': {
      id: '/media-hub'
      path: '/media-hub'
      fullPath: '/media-hub'
      preLoaderRoute: typeof MediaHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manhaj': {
      id: '/manhaj'
      path: '/manhaj'
      fullPath: '/manhaj'
      preLoaderRoute: typeof ManhajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duties': {
      id: '/duties'
      path: '/duties'
      fullPath: '/duties'
      preLoaderRoute: typeof DutiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ala-baseera': {
      id: '/ala-baseera'
      path: '/ala-baseera'
      fullPath: '/ala-baseera'
      preLoaderRoute: typeof AlaBaseeraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/': {
      id: '/network/'
      path: '/'
      fullPath: '/network/'
      preLoaderRoute: typeof NetworkIndexRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/student/$token': {
      id: '/student/$token'
      path: '/student/$token'
      fullPath: '/student/$token'
      preLoaderRoute: typeof StudentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/$unitId': {
      id: '/network/$unitId'
      path: '/$unitId'
      fullPath: '/network/$unitId'
      preLoaderRoute: typeof NetworkUnitIdRouteImport
      parentRoute: typeof NetworkRoute
    }
    '/mosque/$mosqueId': {
      id: '/mosque/$mosqueId'
      path: '/mosque/$mosqueId'
      fullPath: '/mosque/$mosqueId'
      preLoaderRoute: typeof MosqueMosqueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NetworkRouteChildren {
  NetworkUnitIdRoute: typeof NetworkUnitIdRoute
  NetworkIndexRoute: typeof NetworkIndexRoute
}

const NetworkRouteChildren: NetworkRouteChildren = {
  NetworkUnitIdRoute: NetworkUnitIdRoute,
  NetworkIndexRoute: NetworkIndexRoute,
}

const NetworkRouteWithChildren =
  NetworkRoute._addFileChildren(NetworkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlaBaseeraRoute: AlaBaseeraRoute,
  CompetitionRoute: CompetitionRoute,
  DesignSystemRoute: DesignSystemRoute,
  DutiesRoute: DutiesRoute,
  FinanceRoute: FinanceRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ManhajRoute: ManhajRoute,
  MediaHubRoute: MediaHubRoute,
  MyCirclesRoute: MyCirclesRoute,
  MyCommitteeRoute: MyCommitteeRoute,
  NetworkRoute: NetworkRouteWithChildren,
  NoAccessRoute: NoAccessRoute,
  RegisterRoute: RegisterRoute,
  MosqueMosqueIdRoute: MosqueMosqueIdRoute,
  StudentTokenRoute: StudentTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
